export const columns = [
  { id: "Users", label: "Users", minWidth: 150 },
  { id: "OrderValue", label: "Order Value", minWidth: 120 },
  {
    id: "Quantity",
    label: "Quantity",
    minWidth: 150,
  },
  {
    id: "OrderID",
    label: "Order ID",
    minWidth: 100,
  },
  {
    id: "ExpectedDelivery",
    label: "Expected Delivery",
    minWidth: 150,
  },
  {
    id: "Status",
    label: "Status",
    minWidth: 150,
  },
];

export const OrdersList = [
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Delayed",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Confirmed",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Returned",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Out for delivery",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Delayed",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Confirmed",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Returned",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Out for delivery",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Delayed",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Confirmed",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Returned",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Out for delivery",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Delayed",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Confirmed",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Returned",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Out for delivery",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Delayed",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Confirmed",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Returned",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Out for delivery",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Delayed",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Confirmed",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Returned",
  },
  {
    products: "Paint Image",
    orderValue: "$4306",
    quantity: 43,
    orderID: 7535,
    expectedDelivery: "11/12/24",
    status: "Out for delivery",
  },
];
